spring:
  profiles:
    active: local
    group:
      local: console-logging
      prod: real-slack, file-info-logging, file-error-logging, slack-prod-error-logging,
---
spring:
  config:
    activate:
      on-profile: local
image:
  path: C:\\Users\\joel6\\Desktop\\
---
spring:
  config:
    activate:
      on-profile: prod
image:
  path: /home/ubuntu/images/
logging:
  file:
    path: /home/ubuntu/
